### PR TITLE
Issue #21 Consume a factory of ExecutorService to run the disk store

### PR DESCRIPTION
**Pull request by chrisdennis**

### CODE REVIEW

**Comment by terracotta-org** [comment]
Can one of the admins verify this patch?

**Comment by ljacomet** [comment]
This change looks like it has API impact, which means the version should move to 2.2.x

If agreed, that change should be part of the PR.

**Comment by chrisdennis** [comment]
I didn't think about this too closely... but the erased types haven't changed, and the generic type parameters have only been loosened.  I think this should be backwards compatible.  Is that good enough @ljacomet or would you rather us move to 2.2.0 anyway?

**Comment by ljacomet** [comment]
Indeed, just had a look at the PR and did not look at the type relations.

Sounds good to me as a minor update on 2.1.x then - merging

**Pull request merged**
